export const ORDER_LIST_REQUEST='ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS='ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAILURE='ORDER_LIST_FAILURE'
export const ORDER_LIST_RESET='ORDER_LIST_RESET'

export const GET_ORDER_LIST_REQUEST='GET_ORDER_LIST_REQUEST'
export const GET_ORDER_LIST_SUCCESS='GET_ORDER_LIST_SUCCESS'
export const GET_ORDER_LIST_FAILURE='GET_ORDER_LIST_FAILURE'

export const ORDER_PAY_REQUEST='ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS='ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAILURE='ORDER_PAY_FAILURE'
export const ORDER_PAY_RESET='ORDER_PAY_RESET'

export const ADMIN_ORDER_LIST_REQUEST='ADMIN_ORDER_LIST_REQUEST'
export const ADMIN_ORDER_LIST_SUCCESS='ADMIN_ORDER_LIST_SUCCESS'
export const ADMIN_ORDER_LIST_FAILURE='ADMIN_ORDER_LIST_FAILURE'

export const SELLER_ORDER_LIST_REQUEST='SELLER_ORDER_LIST_REQUEST'
export const SELLER_ORDER_LIST_SUCCESS='SELLER_ORDER_LIST_SUCCESS'
export const SELLER_ORDER_LIST_FAILURE='SELLER_ORDER_LIST_FAILURE'
